version: "3.9"

services:
  twemproxy:
    image: "malexer/twemproxy"
    ports:
      - "6380:6380"
    volumes:
      - ./twemproxy.conf:/etc/nutcracker.conf
    command: nutcracker --verbose=6 -c /etc/nutcracker.conf
    depends_on:
      - redis1
      - redis2
      - redis3
  redis1:
    image: "redis"
    command: redis-server --loglevel verbose 
  redis2:
    image: "redis"
    command: redis-server --loglevel verbose
  redis3:
    image: "redis"
    cap_add:
      - NET_ADMIN
    entrypoint: /bin/bash
    command: -c 'apt update; apt install iproute2 iputils-ping -y; tc qdisc add dev eth0 root netem delay 3000ms && redis-server --loglevel verbose; docker-entrypoint.sh redis-server --loglevel verbose'
